server:
  port: 8882

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: video-service-route
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**